services:
  # Postgres server to store injection data (not including
  # screenshots which are stored separately).
  # NOTE: If you're using an external SQL server, you can comment
  # out this service.
  # WARNING: This database gives the "postgres" user admin priveleges
  # with a default password of "xsshunterexpress". Do not expose it
  # externally. If you do, be sure to change the password.
  xsshunterexpress-db:
    image: postgres
    container_name: xsshunterexpress-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # This is a volume mounted into the container
      # (see the directory ./postgres-db-data)
      # So the database will be persisted across
      # container deletion.
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - traefik-net
      - xss-hunter-net 
      
  xsshunterexpress-service:
    build: .
    container_name: xsshunterexpress-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Stores the SSL/TLS certificates and keys
      # in the "ssldata" directory.
      # Your certificates are automatically renewed
      # via LetsEncrypt, no extra work needed!
      # - ./ssldata:/app/greenlock.d
      # Directory where payload fire images are stored.
      - payloads-data:/app/payload-fire-images
      - ~/.config/gcloud/application_default_credentials.json:/gcloud.json
    # Comment out if you're using an external SQL
    # server and have commented out the DB section.
    depends_on:
      xsshunterexpress-db:
        condition: service_healthy
    
    networks:
      - traefik-net
      - xss-hunter-net 

  xsshunterexpress-trufflehog:
    build:
      dockerfile: Dockerfile.trufflehog
    container_name: xsshunterexpress-trufflehog
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - traefik-net
      - xss-hunter-net 


  # xsshunterexpress-proxy:
  #   image: caddy:alpine
  #   container_name: xsshunterexpress-proxy
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./caddy/data:/data
  #     - ./caddy/config:/config
  #     - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  payloads-data:
  db-data:

networks:
  traefik-net:
    name: pm_traefik-net
  xss-hunter-net:
    name: xss-hunter_default